(function() {var implementors = {};
implementors['unicode_bidi'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='unicode_bidi/tables/enum.BidiClass.html' title='unicode_bidi::tables::BidiClass'>BidiClass</a>",];implementors['idna'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='idna/uts46/struct.Flags.html' title='idna::uts46::Flags'>Flags</a>",];implementors['url'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='url/enum.ParseError.html' title='url::ParseError'>ParseError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='url/enum.Position.html' title='url::Position'>Position</a>","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='url/form_urlencoded/struct.Parse.html' title='url::form_urlencoded::Parse'>Parse</a>&lt;'a&gt;","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='url/percent_encoding/struct.SIMPLE_ENCODE_SET.html' title='url::percent_encoding::SIMPLE_ENCODE_SET'>SIMPLE_ENCODE_SET</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='url/percent_encoding/struct.QUERY_ENCODE_SET.html' title='url::percent_encoding::QUERY_ENCODE_SET'>QUERY_ENCODE_SET</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='url/percent_encoding/struct.DEFAULT_ENCODE_SET.html' title='url::percent_encoding::DEFAULT_ENCODE_SET'>DEFAULT_ENCODE_SET</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='url/percent_encoding/struct.PATH_SEGMENT_ENCODE_SET.html' title='url::percent_encoding::PATH_SEGMENT_ENCODE_SET'>PATH_SEGMENT_ENCODE_SET</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='url/percent_encoding/struct.USERINFO_ENCODE_SET.html' title='url::percent_encoding::USERINFO_ENCODE_SET'>USERINFO_ENCODE_SET</a>","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='url/struct.ParseOptions.html' title='url::ParseOptions'>ParseOptions</a>&lt;'a&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
