(function() {var implementors = {};
implementors['url'] = ["impl&lt;S: <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html' title='core::convert::AsRef'>AsRef</a>&lt;<a class='primitive' href='https://doc.rust-lang.org/nightly/std/primitive.str.html'>str</a>&gt;&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='enum' href='url/enum.Host.html' title='url::Host'>Host</a>&lt;S&gt;","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='enum' href='url/enum.ParseError.html' title='url::ParseError'>ParseError</a>","impl&lt;'a, E: <a class='trait' href='url/percent_encoding/trait.EncodeSet.html' title='url::percent_encoding::EncodeSet'>EncodeSet</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='struct' href='url/percent_encoding/struct.PercentEncode.html' title='url::percent_encoding::PercentEncode'>PercentEncode</a>&lt;'a, E&gt;","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='struct' href='url/struct.Url.html' title='url::Url'>Url</a>",];implementors['oauth2'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='enum' href='oauth2/enum.ClientType.html' title='oauth2::ClientType'>ClientType</a>",];implementors['oauth2'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='enum' href='oauth2/enum.ClientType.html' title='oauth2::ClientType'>ClientType</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
